# Generated by Django 5.0.7 on 2024-08-08 15:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bank',
            fields=[
                ('bank_id', models.AutoField(primary_key=True, serialize=False)),
                ('bank_name', models.CharField(max_length=255)),
                ('bank_branch', models.CharField(max_length=255)),
                ('account_number', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Officer',
            fields=[
                ('officer_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='PaymentMode',
            fields=[
                ('payment_mode_id', models.AutoField(primary_key=True, serialize=False)),
                ('payment_mode', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Root',
            fields=[
                ('root_id', models.AutoField(primary_key=True, serialize=False)),
                ('root_name', models.CharField(max_length=255)),
                ('root_code', models.CharField(max_length=50)),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='RootTransportAgent',
            fields=[
                ('root_transport_agent_id', models.AutoField(primary_key=True, serialize=False)),
                ('agent_name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Supervision',
            fields=[
                ('supervision_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('user_id', models.AutoField(primary_key=True, serialize=False)),
                ('user_name', models.CharField(max_length=255)),
                ('password', models.CharField(max_length=255)),
                ('status', models.BooleanField(default=True)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='UserRole',
            fields=[
                ('user_role_id', models.AutoField(primary_key=True, serialize=False)),
                ('user_role', models.CharField(max_length=255)),
                ('status', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Loan',
            fields=[
                ('loan_id', models.AutoField(primary_key=True, serialize=False)),
                ('date', models.DateField()),
                ('loan_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('cheque_number', models.CharField(blank=True, max_length=50, null=True)),
                ('payment_mode', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='trs.paymentmode')),
                ('root', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='trs.root')),
            ],
        ),
        migrations.CreateModel(
            name='RootTransport',
            fields=[
                ('root_transport_id', models.AutoField(primary_key=True, serialize=False)),
                ('root', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='trs.root')),
                ('transport_agent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='trs.roottransportagent')),
            ],
        ),
        migrations.CreateModel(
            name='Supplier',
            fields=[
                ('supplier_id', models.AutoField(primary_key=True, serialize=False)),
                ('record_id', models.CharField(max_length=255)),
                ('supplier_name', models.CharField(max_length=255)),
                ('date', models.DateField()),
                ('contact_info', models.CharField(max_length=255)),
                ('address', models.TextField()),
                ('land_size', models.DecimalField(decimal_places=2, max_digits=10)),
                ('bank', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='trs.bank')),
            ],
        ),
        migrations.CreateModel(
            name='LoanRepayment',
            fields=[
                ('loan_repayment_id', models.AutoField(primary_key=True, serialize=False)),
                ('date', models.DateField()),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('balance', models.DecimalField(decimal_places=2, max_digits=10)),
                ('loan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='trs.loan')),
                ('root', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='trs.root')),
                ('supplier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='trs.supplier')),
            ],
        ),
        migrations.AddField(
            model_name='loan',
            name='supplier',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='trs.supplier'),
        ),
        migrations.CreateModel(
            name='DailyGreenLeaf',
            fields=[
                ('daily_green_leaf_id', models.AutoField(primary_key=True, serialize=False)),
                ('date', models.DateField()),
                ('full_quantity', models.DecimalField(decimal_places=2, max_digits=10)),
                ('leaves_quantity', models.DecimalField(decimal_places=2, max_digits=10)),
                ('gold_leaves', models.DecimalField(decimal_places=2, max_digits=10)),
                ('empty_cases', models.IntegerField()),
                ('water', models.DecimalField(decimal_places=2, max_digits=10)),
                ('matured_leaves', models.DecimalField(decimal_places=2, max_digits=10)),
                ('boiled_leaves', models.DecimalField(decimal_places=2, max_digits=10)),
                ('good_leaves', models.DecimalField(decimal_places=2, max_digits=10)),
                ('officer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='trs.officer')),
                ('root', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='trs.root')),
                ('root_transport_agent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='trs.roottransportagent')),
                ('supervision', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='trs.supervision')),
                ('supplier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='trs.supplier')),
            ],
        ),
        migrations.CreateModel(
            name='AdvancePayment',
            fields=[
                ('advance_payment_id', models.AutoField(primary_key=True, serialize=False)),
                ('date', models.DateField()),
                ('advance_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('cheque_number', models.CharField(blank=True, max_length=50, null=True)),
                ('payment_mode', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='trs.paymentmode')),
                ('root', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='trs.root')),
                ('supplier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='trs.supplier')),
            ],
        ),
        migrations.CreateModel(
            name='SupplierPayment',
            fields=[
                ('supplier_payment_id', models.AutoField(primary_key=True, serialize=False)),
                ('transaction_date', models.DateTimeField()),
                ('quantity', models.IntegerField()),
                ('cheque_number', models.CharField(blank=True, max_length=50, null=True)),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('payment_mode', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='trs.paymentmode')),
                ('supplier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='trs.supplier')),
            ],
        ),
        migrations.AddField(
            model_name='supervision',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='trs.user'),
        ),
        migrations.AddField(
            model_name='officer',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='trs.user'),
        ),
        migrations.AddField(
            model_name='user',
            name='user_role',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='trs.userrole'),
        ),
    ]
