# Generated by Django 5.0.7 on 2024-08-03 15:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bank',
            fields=[
                ('bank_id', models.AutoField(primary_key=True, serialize=False)),
                ('bank_name', models.CharField(max_length=255)),
                ('bank_branch', models.CharField(max_length=255)),
                ('account_number', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Officer',
            fields=[
                ('Officer_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Root',
            fields=[
                ('root_id', models.AutoField(primary_key=True, serialize=False)),
                ('root_name', models.CharField(max_length=255)),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Supervision',
            fields=[
                ('supervision_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Supplier',
            fields=[
                ('supplier_id', models.AutoField(primary_key=True, serialize=False)),
                ('record_id', models.CharField(max_length=255)),
                ('supplier_name', models.CharField(max_length=255)),
                ('date', models.DateField()),
                ('full_quantity', models.DecimalField(decimal_places=2, max_digits=10)),
                ('leaves_quantity', models.DecimalField(decimal_places=2, max_digits=10)),
                ('gold_leaves', models.DecimalField(decimal_places=2, max_digits=10)),
                ('empty_cases', models.IntegerField()),
                ('water', models.DecimalField(decimal_places=2, max_digits=10)),
                ('matured_leaves', models.DecimalField(decimal_places=2, max_digits=10)),
                ('boiled_leaves', models.DecimalField(decimal_places=2, max_digits=10)),
                ('good_leaves', models.DecimalField(decimal_places=2, max_digits=10)),
                ('contact_info', models.CharField(max_length=255)),
                ('address', models.TextField()),
                ('bank', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='trs.bank')),
                ('officer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='trs.officer')),
                ('supervision', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='trs.supervision')),
            ],
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('transaction_id', models.AutoField(primary_key=True, serialize=False)),
                ('customer_id', models.IntegerField()),
                ('transaction_date', models.DateTimeField()),
                ('quantity', models.IntegerField()),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('root', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='trs.root')),
                ('supplier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='trs.supplier')),
            ],
        ),
    ]
