# Generated by Django 5.0.7 on 2024-08-05 12:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trs', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='officer',
            old_name='Officer_id',
            new_name='officer_id',
        ),
        migrations.RemoveField(
            model_name='supplier',
            name='boiled_leaves',
        ),
        migrations.RemoveField(
            model_name='supplier',
            name='empty_cases',
        ),
        migrations.RemoveField(
            model_name='supplier',
            name='full_quantity',
        ),
        migrations.RemoveField(
            model_name='supplier',
            name='gold_leaves',
        ),
        migrations.RemoveField(
            model_name='supplier',
            name='good_leaves',
        ),
        migrations.RemoveField(
            model_name='supplier',
            name='leaves_quantity',
        ),
        migrations.RemoveField(
            model_name='supplier',
            name='matured_leaves',
        ),
        migrations.RemoveField(
            model_name='supplier',
            name='officer',
        ),
        migrations.RemoveField(
            model_name='supplier',
            name='supervision',
        ),
        migrations.RemoveField(
            model_name='supplier',
            name='water',
        ),
        migrations.CreateModel(
            name='AdvancePayment',
            fields=[
                ('advance_payment_id', models.AutoField(primary_key=True, serialize=False)),
                ('date', models.DateField()),
                ('advance_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('root', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='trs.root')),
                ('supplier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='trs.supplier')),
            ],
        ),
        migrations.CreateModel(
            name='DailyGreenLeaf',
            fields=[
                ('daily_green_leaf_id', models.AutoField(primary_key=True, serialize=False)),
                ('date', models.DateField()),
                ('full_quantity', models.DecimalField(decimal_places=2, max_digits=10)),
                ('leaves_quantity', models.DecimalField(decimal_places=2, max_digits=10)),
                ('gold_leaves', models.DecimalField(decimal_places=2, max_digits=10)),
                ('empty_cases', models.IntegerField()),
                ('water', models.DecimalField(decimal_places=2, max_digits=10)),
                ('matured_leaves', models.DecimalField(decimal_places=2, max_digits=10)),
                ('boiled_leaves', models.DecimalField(decimal_places=2, max_digits=10)),
                ('good_leaves', models.DecimalField(decimal_places=2, max_digits=10)),
                ('officer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='trs.officer')),
                ('root', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='trs.root')),
                ('supervision', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='trs.supervision')),
                ('supplier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='trs.supplier')),
            ],
        ),
        migrations.CreateModel(
            name='Loan',
            fields=[
                ('loan_id', models.AutoField(primary_key=True, serialize=False)),
                ('date', models.DateField()),
                ('loan_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('root', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='trs.root')),
                ('supplier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='trs.supplier')),
            ],
        ),
        migrations.CreateModel(
            name='LoanRepayment',
            fields=[
                ('loan_repayment_id', models.AutoField(primary_key=True, serialize=False)),
                ('date', models.DateField()),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('balance', models.DecimalField(decimal_places=2, max_digits=10)),
                ('loan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='trs.loan')),
                ('root', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='trs.root')),
                ('supplier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='trs.supplier')),
            ],
        ),
        migrations.CreateModel(
            name='RootTransportAgent',
            fields=[
                ('root_transport_agent_id', models.AutoField(primary_key=True, serialize=False)),
                ('agent_name', models.CharField(max_length=255)),
                ('supplier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='trs.supplier')),
            ],
        ),
        migrations.CreateModel(
            name='RootTransport',
            fields=[
                ('root_transport_id', models.AutoField(primary_key=True, serialize=False)),
                ('root', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='trs.root')),
                ('transport_agent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='trs.roottransportagent')),
            ],
        ),
        migrations.CreateModel(
            name='SupplierPayment',
            fields=[
                ('supplier_payment_id', models.AutoField(primary_key=True, serialize=False)),
                ('transaction_date', models.DateTimeField()),
                ('quantity', models.IntegerField()),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('root', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='trs.root')),
                ('supplier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='trs.supplier')),
            ],
        ),
        migrations.DeleteModel(
            name='Transaction',
        ),
    ]
